### ISSUE TITLE
No crawl.html template

### ISSUE THREAD

**Issue by alaw005** [opensemanticsearch/open-semantic-search-apps#10]
Row 45 of /src/datasources/views.py has the following line:

`return render(request, 'crawl.html',` 

But there is no `crawl.html` template

**Comment by Mandalka** [comment]
Affected "only" printing the status message if indexing web pages once without adding crawling entry. [Fixed](https://github.com/opensemanticsearch/open-semantic-search-apps/commit/b3dd576932e2c7700abc04ce783473737d018455).
