### ISSUE TITLE
Error 500 when accessing search-apps from the LAN

### ISSUE THREAD

**Issue by hpiedcoq** [opensemanticsearch/open-semantic-search-apps#11]
Hi,

OSS is installed on a server on my LAN and I want my user to use it threw there web browser.
The search part works like a charm, but I can't access the search-app url and always get an ERROR 500.

I suspect something around Django's config; like ALLOWED_HOSTS.

Any hint on that?

Thank you!

**Comment by opensemanticsearch** [comment]
Which Linux distribution/version?
Which package/version of the search engine?
Is there more log, f.e. in /var/log/apache2/error.log ?

**Comment by hpiedcoq** [comment]
Thank you for your quick answer.
Ubuntu 16.04, Solr 6.5.1, the install was made last thursday by downloading the deb pack then sudo dpkg -i and dependencies installed.

Here is my firewall rules : 

`administrateur@IL1-AT-PARI:~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8983
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:7574
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:3389
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:5910

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere`

Here is the result of tail -f /varl/log/apache2/access.log

`10.3.7.55 - - [06/Oct/2017:03:20:37 +0000] "GET /search-apps/thesaurus/ HTTP/1.1" 500 823 "http://recherche.XXXXXparis.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms" "Mozilla/5.0 (Windows NT 6.1; rv:50.0) Gecko/20100101 Firefox/50.0"
127.0.0.1 - - [06/Oct/2017:03:20:47 +0000] "GET /search-apps/thesaurus/1/ HTTP/1.1" 200 1336 "http://localhost/search-apps/thesaurus/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [06/Oct/2017:03:20:47 +0000] "GET /static/js/vendor/modernizr.js HTTP/1.1" 200 4976 "http://localhost/search-apps/thesaurus/1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [06/Oct/2017:03:20:47 +0000] "GET /static/js/vendor/fastclick.js HTTP/1.1" 200 2793 "http://localhost/search-apps/thesaurus/1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [06/Oct/2017:03:20:47 +0000] "GET /static/js/foundation/foundation.js HTTP/1.1" 200 5448 "http://localhost/search-apps/thesaurus/1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [06/Oct/2017:03:20:47 +0000] "GET /static/js/foundation/foundation.tab.js HTTP/1.1" 200 2325 "http://localhost/search-apps/thesaurus/1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [06/Oct/2017:03:20:47 +0000] "GET /static/js/foundation/foundation.topbar.js HTTP/1.1" 200 3364 "http://localhost/search-apps/thesaurus/1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [06/Oct/2017:03:20:47 +0000] "GET /static/js/foundation.min.js HTTP/1.1" 200 23127 "http://localhost/search-apps/thesaurus/1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [06/Oct/2017:03:20:47 +0000] "GET /static/js/vendor/jquery.js HTTP/1.1" 200 30171 "http://localhost/search-apps/thesaurus/1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [06/Oct/2017:03:20:47 +0000] "GET /static/css/foundation.css HTTP/1.1" 200 20145 "http://localhost/search-apps/thesaurus/1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
::1 - - [06/Oct/2017:03:20:53 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/3.5.2 (internal dummy connection)" `

As you see the localhost sees the page, but not 10.3.7.55.
What is strange is that 10.3.7.55 can reach the search page but not the search-app page.

**Comment by opensemanticsearch** [comment]
The search (PHP) and search apps (Django/Python) are different systems, so one might work even if another environment is misconfigured.

Can the app page not be accessed (f.e. password protection problems, did you set up password protection?) or error (500) ?
If error, please have a look to the apache log error.log instead of access.log ...

**Comment by hpiedcoq** [comment]
Oups sure.
no password protection : 


error log : 

`[Fri Oct 06 03:20:37.555113 2017] [wsgi:error] [pid 6796] [client 10.3.7.55:57624]     obj = self.var.resolve(context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:20:37.555118 2017] [wsgi:error] [pid 6796] [client 10.3.7.55:57624]   File "/usr/lib/python3/dist-packages/django/template/base.py", line 789, in resolve, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:20:37.555120 2017] [wsgi:error] [pid 6796] [client 10.3.7.55:57624]     value = self._resolve_lookup(context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:20:37.555124 2017] [wsgi:error] [pid 6796] [client 10.3.7.55:57624]   File "/usr/lib/python3/dist-packages/django/template/base.py", line 849, in _resolve_lookup, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:20:37.555127 2017] [wsgi:error] [pid 6796] [client 10.3.7.55:57624]     current = current(), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:20:37.555131 2017] [wsgi:error] [pid 6796] [client 10.3.7.55:57624]   File "/usr/lib/python3/dist-packages/django/http/request.py", line 152, in build_absolute_uri, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:20:37.555134 2017] [wsgi:error] [pid 6796] [client 10.3.7.55:57624]     host=self.get_host(),, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:20:37.555138 2017] [wsgi:error] [pid 6796] [client 10.3.7.55:57624]   File "/usr/lib/python3/dist-packages/django/http/request.py", line 102, in get_host, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:20:37.555140 2017] [wsgi:error] [pid 6796] [client 10.3.7.55:57624]     raise DisallowedHost(msg), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:20:37.555150 2017] [wsgi:error] [pid 6796] [client 10.3.7.55:57624] django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'recherche.XXXXX-paris.fr'. You may need to add 'recherche.XXXXX-paris.fr' to ALLOWED_HOSTS., referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.821549 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632] mod_wsgi (pid=20111): Exception occurred processing WSGI script '/var/lib/opensemanticsearch/opensemanticsearch/wsgi.py'., referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823261 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632] Traceback (most recent call last):, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823354 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 108, in get_response, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823370 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     response = middleware_method(request), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823397 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/middleware/common.py", line 62, in process_request, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823443 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     host = request.get_host(), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823484 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/http/request.py", line 102, in get_host, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823496 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     raise DisallowedHost(msg), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823545 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632] django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'recherche.XXXXX-paris.fr'. You may need to add 'recherche.XXXXX-paris.fr' to ALLOWED_HOSTS., referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823565 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632] , referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823598 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632] During handling of the above exception, another exception occurred:, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823604 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632] , referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823650 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632] Traceback (most recent call last):, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823740 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823752 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     response = self.get_response(request), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823759 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 207, in get_response, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823803 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     return debug.technical_500_response(request, *sys.exc_info(), status_code=400), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823824 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/views/debug.py", line 97, in technical_500_response, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823865 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     html = reporter.get_traceback_html(), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823906 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/views/debug.py", line 384, in get_traceback_html, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823923 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     return t.render(c), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823931 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/template/base.py", line 210, in render, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.823965 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     return self._render(context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824008 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/template/base.py", line 202, in _render, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824019 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     return self.nodelist.render(context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824025 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824028 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     bit = self.render_node(node, context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824073 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/template/debug.py", line 79, in render_node, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824104 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     return node.render(context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824141 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 329, in render, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824152 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     return nodelist.render(context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824160 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824190 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     bit = self.render_node(node, context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824224 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/template/debug.py", line 79, in render_node, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824234 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     return node.render(context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824241 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/template/debug.py", line 89, in render, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824259 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     output = self.filter_expression.resolve(context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824270 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/template/base.py", line 648, in resolve, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824274 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     obj = self.var.resolve(context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824303 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/template/base.py", line 789, in resolve, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824307 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     value = self._resolve_lookup(context), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824322 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/template/base.py", line 849, in _resolve_lookup, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824325 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     current = current(), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824336 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/http/request.py", line 152, in build_absolute_uri, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824344 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     host=self.get_host(),, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824350 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]   File "/usr/lib/python3/dist-packages/django/http/request.py", line 102, in get_host, referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824352 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632]     raise DisallowedHost(msg), referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
[Fri Oct 06 03:43:13.824378 2017] [wsgi:error] [pid 20111] [client 10.3.7.55:57632] django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'recherche.XXXXX-paris.fr'. You may need to add 'recherche.XXXXX-paris.fr' to ALLOWED_HOSTS., referer: http://recherche.XXXXX-paris.fr/search/?q=test&operator=OR&stemming=stemming&synonyms=synonyms
`

**Comment by hpiedcoq** [comment]
definetely something to see with allowed_host which is declared [] if I remember well another error I got the other day.
But I don't know in which file I have to modify it.

**Comment by opensemanticsearch** [comment]
The problem was the access settings in the Django project config, no bug/error.

The new default settings allow access from the network, too.

**Comment by hpiedcoq** [comment]
Thanks for correcting this.
My OSS machine is completely disconnected from internet for security reason. I cannot bring it back on the net.
How can I patch this? Is it just the Allowed_Host thing?

**Comment by hpiedcoq** [comment]
Ok, a simple dpkg -i updatedpackage.deb will patch it. Thanks for the good work.
