### ISSUE TITLE
Admin user name and password are not mentioned in the documentation.

### ISSUE THREAD

**Issue by desirockstar** [opensemanticsearch/open-semantic-search-apps#15]
Admin user name and password are not mentioned in the documentation.

Below is the transcript from the documentation. 

> The initial password for the Django admin interface (i.e. for adding tags that are usable for documents tagging) is live.

Tried the below password with following user names:
_user
django
admin
root_

**Comment by Mandalka** [comment]
The admin access for Django/facet configs can be set after getting root by su by
python3 manage.py createsuperuser
within the directory /var/lib/opensemanticsearch

I'll add admin live to Open Semantic Desktop search VM automatically and for Search Appliance VM which is open to the network to documentation for security issues to have no default password set.

**Comment by opensemanticsearch** [comment]
Added to documentation.

Since not accessable from network, this will be preconfigured with default password for Open Semantic Desktop Search VM in https://github.com/opensemanticsearch/open-semantic-search/issues/24
