### ISSUE TITLE
Move/merge extraction of labels from ontologies for faceted search to ontology module

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search-apps#17]
Move/Merge extraction of labels in ontologies to the external ontology module for synonym config creation so each ontolgy has only to be loaded once after changes, which will increase performance of import of large ontolgies.

**Comment by Mandalka** [comment]
Moved functionality from view function to existing external ontology module, so while import/config generation each ontology has only to be loaded once, which needs less time.
