### ISSUE TITLE
Absolute paths in FileField's 'upload_to' causes Django Migration failure

### ISSUE THREAD

**Issue by caelor** [opensemanticsearch/open-semantic-search-apps#18]
Installing to a newly installed Ubuntu 17.10 VM using the `open-semantic-search_18.01.19.deb` package, was unable to access Datasources or Thesaurus. Tracked it back to `/var/lib/opensemanticsearch/db.sqlite3` being empty as Django migration had failed during install.

Trying to manually run migrations resulted in:

```
# python3 manage.py migrate
SystemCheckError: System check identified some issues:

ERRORS:
csv_manager.CSV_Manager.file: (fields.E202) FileField's 'upload_to' argument must be a relative path, not an absolute path.
	HINT: Remove the leading slash.
ontologies.Ontologies.file: (fields.E202) FileField's 'upload_to' argument must be a relative path, not an absolute path.
	HINT: Remove the leading slash.

WARNINGS:
thesaurus.Concept.groups: (fields.W340) null has no effect on ManyToManyField.
```

https://github.com/opensemanticsearch/open-semantic-search-apps/blob/3260c489ad29cfb27d9e847127e5067b733087af/src/csv_manager/models.py#L12

https://github.com/opensemanticsearch/open-semantic-search-apps/blob/3260c489ad29cfb27d9e847127e5067b733087af/src/ontologies/models.py#L16

Changing both of these to be relative rather than absolute paths allowed the DB migration to complete and removed to UI errors when browsing to Datasources and Thesaurus.

**Comment by Mandalka** [comment]
Thanks for you bug report. The packages are running with this settings for the LTS versions. This happens if new Django version on newer Ubuntu versions and Debian testing.

Will change that so it runs on all.

**Comment by caelor** [comment]
Thanks. I was conscious that Ubuntu 18.04 is schedule to be a new LTS build so I thought it was worth raising to be ready.

**Comment by Mandalka** [comment]
If there are errors for example on [crawling](https://github.com/opensemanticsearch/open-semantic-search/issues/76) because of that:

After setting to relative paths you can do 
cd /var/lib/opensemanticsearch
python3 manage.py migrate
so the DB upgrade should work with newer Django versions, too instead of failing because of absolute path settings.

**Comment by hpiedcoq** [comment]
Thanks for driving me here.

So as far as I understand I have to remove the leading slash of both : 



```
open-semantic-search-apps/src/csv_manager/models.py

Line 12 in 3260c48
 file = models.FileField(upload_to='**/**var/opensemanticsearch/csv', blank = True) 
```
and 
```
open-semantic-search-apps/src/ontologies/models.py

Line 16 in 3260c48
file = models.FileField(upload_to='**/**var/opensemanticsearch/ontologies', blank = True) 
```

I did it then try to 
```
cd /var/lib/opensemanticsearch
python3 manage.py migrate
```
but it doesn't work.

**Comment by Mandalka** [comment]
With https://github.com/opensemanticsearch/open-semantic-search-apps/commit/9a2e6e573fa135623d1981662e33ecc5823e1f5d the Django apps now use relative paths for management of uploads, so new installations / the new package should run on new Django and coming Ubuntu LTS version, too.

If Linux is upgraded on an existing installations, you have to remove the leading path /var/lib/opensemanticsearch/ from the paths csv and ontologies in your Django database located in /var/lib/opensemanticsearch/db.sqlite3 ...

If a fresh installation (no entries in database!) failed, just delete the database /var/lib/opensemanticsearch/db.sqlite3 before upgrade with new package.
