### ISSUE TITLE
Use REST-API for Solr config

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search-apps#19]
Use REST-API for synonyms config instead of config file, so we can use Solr on separates server(s) over network without sharing files, which makes scaling & separation of Docker containers and integration with Elastic search easier.

**Comment by opensemanticsearch** [comment]
Check if it is possible to use solr.KeepWordFilterFactory with managed resources API like ManagedWordSetResource, too.

So we could do Named Entities config by REST-API (managed schema API for fields and managed resources API for named entities), too.

**Comment by Mandalka** [comment]
Solr field config of named entity dictionaries now done by Solr REST API by the new Open Semantic Entity Search API component dictionary manager.

**Comment by opensemanticsearch** [comment]
With the new Solr tagger https://github.com/opensemanticsearch/open-semantic-entity-search-api/issues/31 we do not need KeepWordFilterFactory anymore and all can be done by REST.
