### ISSUE TITLE
Migrate facet field names to Tika style

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search-apps#23]
Migrate facet field names to Tika style + Solr 7 field type suffix:

'message_from_ss' to 'Message-From_ss'
'message_to_ss' to 'Message-To_ss'
'message_cc_ss' to	'Message-CC_ss'
 'message_bcc_ss' to 'Message-BCC_ss'

**Comment by Mandalka** [comment]
Migrated field names in facets DB by https://github.com/opensemanticsearch/open-semantic-search-apps/commit/677ab32589397cad4fe89bd5b192fbd5f6f07274
