### ISSUE TITLE
Setup of initial graph visualization parameters

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search-apps#26]
UI for setup of graph visualization parameters in facets config and export to search UI config for custom graph parameters for each property/class/facet.

**Comment by Mandalka** [comment]
Initial/Default graph visualization entities/classes/properties now dynamic from config/database.

You can set fields/facets/classes/properties to default graph visualization fields by facet config field graph_enabled.
