### ISSUE TITLE
Can't delete a file via REST-API

### ISSUE THREAD

**Issue by alzmich** [opensemanticsearch/open-semantic-search-apps#29]
Hi,

i can't delete a file via the REST-API - It always throws an Exception:
name 'delete' is not defined

URL was correct (http://<server>/search-apps/api/delete?uri=file:///tmp/testfile)
For me the solution was to edit the views.py and add  "from opensemanticetl.tasks import delete", like:

/var/lib/opensemanticsearch/api/views.py:
  5 import json
  6 
  7 from opensemanticetl.tasks import delete
  8 from opensemanticetl.tasks import enrich

**Comment by mosea3** [comment]
Hi
Thanks!
I noticed that too, but I was too inexperienced in python to sort this one out.

best regards

Von meinem iPad gesendet

**Comment by Mandalka** [comment]
Tnx for bug report, is fixed by https://github.com/opensemanticsearch/open-semantic-search-apps/commit/2853dc399c58b9ef2d6fd8a39b7431698b4b14f6 and in tomorrows release.
