### ISSUE TITLE
Can't delete directories in files/datasources

### ISSUE THREAD

**Issue by mosea3** [opensemanticsearch/open-semantic-search-apps#32]
Hi
As I never remove datasources I may never have noticed, that there is a delete/remove button missing?

Apparently its not defined anywhere.

**Comment by dregula** [comment]
Same problem here. Was fooling around with search-apps/crawler/, adding various trivial websites, which showed-up nicely on the datasources/Websites tab. Each website has three buttons: Index-Now, Details, and Edit-Settings. I can;t seem to find a way to simply Delete that "website for indexing". (opensemanticsearch-delete --empty didn;t seem to do the trick ;-)
Thanks!

**Comment by networkadminuser** [comment]
Same issue for me, this is still a concern, I still can't find a command line way to delete them cleanly either. Any help would be appreciated.

**Comment by mosea3** [comment]
Hi

I think its time for me to get into this.
Directories to be indexed are stored in a sqlite database. 
So you could manually remove it. 

I‘ll try to adapt the model and controller to enable deletion and get back with a merge request for Markus to check. 

Best regards from switzerland. 

Andy Moser
Student der Medizininformatik BFH
Étudiant en informatique médicale HESB
BFH | TI | Medizininformatik, Biel
Höheweg 18
2501 Biel

Von meinem Smartphone gesendet

**Comment by Mandalka** [comment]
Implemented a "Delete" link in the apps list view, so no need anymore to use the Djang admin ui to delete entries.
