### ISSUE TITLE
Abstract/externalize/modularize named entities dictionary code

### ISSUE THREAD

**Issue by Mandalka** [opensemanticsearch/open-semantic-search-apps#4]
Clean/modularize code for generation and setup of named entities extraction dictionaries, so it can be used more abstract (for example more usable with elastic search) and with cleaner architecture than now in different views of Thesaurus and Ontologies app.

**Comment by opensemanticsearch** [comment]
Export entities dictionaries to ETL config, so it will be usable by [dictionary based named entity extraction by ETL](https://github.com/opensemanticsearch/open-semantic-etl/issues/49) and so can be used for [normalization](https://github.com/opensemanticsearch/open-semantic-search/issues/20) exported to Elastic Search and/or Neo4j graph DB, too.

**Comment by Mandalka** [comment]
Entities are now exported not only to Solr xml schema config, but to Solr independent ETL dictionaries / config files, too.

The main code for export of entities from ontologies is now more modular by Solr Ontology Tagger, not in Django views anymore.

**Comment by Mandalka** [comment]
Entities (and its matching aliases) in facets are now normalized to preferred labels by the new [Open Entity Search API](https://github.com/opensemanticsearch/open-semantic-entity-search-api) entity linker by the new Open Semantic ETL plugin enhance_entity_linking
