### ISSUE TITLE
REST-API & filesystem crawler UI: Paralell processing of files contained in a directory

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search-apps#5]
If REST-API or file system crawler UI parameter filename is an directory instead of single file, do parallel processing (as many workers as processors, like for each file in queue if using API with single filenames) with all contained files.

**Comment by opensemanticsearch** [comment]
Since ETL file tool works parallel if directory, many files inside a directory which will be indexed by API will be processed parallel, too.

Since API now adds tasks to message queue for workers, this is done with managed/limited workers, but it would be better to add not directories but files of them to the queue, so the limit is count of workers or configured on central config not count of workers * cound of processors.

**Comment by Mandalka** [comment]
New opensemanticsearch-index-dir now uses only celery tasks for parallel processing of files.

So we can use this connector in API for better systemwide control and config of concurrency for parallel processing by celery.

**Comment by Mandalka** [comment]
API using celery task for each file for parallel processing of files in directory if using api/index-filedirectory?uri=path
