### ISSUE TITLE
hard coded link to localhost for flower-interface

### ISSUE THREAD

**Issue by DieGoldeneEnte** [opensemanticsearch/open-semantic-search-apps#55]
The link to flower on the datasources page (open-semantic-search-apps/src/datasources/templates/datasources.html) is hardcoded to point to localhost:5555.
When running open-semantic-serach on a different computer/server this is not accessible, as such it would be helpful, to replace localhost with the URL used for the rest of the site.

**Comment by Mandalka** [comment]
In next release you can configure the URL in the new setup UI tab "Servers (URLs)".

Implemented by https://github.com/opensemanticsearch/open-semantic-search-apps/commit/9afb2846f41e86258524b78ea887213e8468ed6a
