### ISSUE TITLE
Sometimes "Internal Server Error"

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search-apps#57]
(Seems especially on newer Debian releases or current installations maybe because newer releases of some dependencies like PIP packages) there is sometimes a "Internal Server Error" but not on every call, so sometimes you have to do multiple/many calls to reproduce it.

Maybe dependency hell of PIP/debian packages? Or an (after evolution of some Python packages using new/other features now) unstable Apache2 config?

Trying to setup WSGI module of Apache to daemon mode (which is recommended by Django).

**Comment by Mandalka** [comment]
I set the wsgi config for Apache2 to daemon mode, now it works for first IP every time, but calls from another IP get the internal server error every time:

/var/log/apache2/error.log:

[Fri Jul 19 13:42:35.021155 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382] mod_wsgi (pid=1198): Failed to exec Python script file '/var/lib/opensemanticsearch/opensemanticsearch/wsgi.py'.
[Fri Jul 19 13:42:35.021237 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382] mod_wsgi (pid=1198): Exception occurred processing WSGI script '/var/lib/opensemanticsearch/opensemanticsearch/wsgi.py'.
[Fri Jul 19 13:42:35.021417 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382] Traceback (most recent call last):
[Fri Jul 19 13:42:35.021475 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382]   File "/var/lib/opensemanticsearch/opensemanticsearch/wsgi.py", line 14, in <module>
[Fri Jul 19 13:42:35.021489 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382]     application = get_wsgi_application()
[Fri Jul 19 13:42:35.021508 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382]   File "/usr/lib/python3/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Fri Jul 19 13:42:35.021525 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382]     django.setup(set_prefix=False)
[Fri Jul 19 13:42:35.021596 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382]   File "/usr/lib/python3/dist-packages/django/__init__.py", line 27, in setup
[Fri Jul 19 13:42:35.021609 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382]     apps.populate(settings.INSTALLED_APPS)
[Fri Jul 19 13:42:35.021626 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382]   File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 78, in populate
[Fri Jul 19 13:42:35.021637 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382]     raise RuntimeError("populate() isn't reentrant")
[Fri Jul 19 13:42:35.021682 2019] [wsgi:error] [pid 1198] [remote 10.0.2.2:53382] RuntimeError: populate() isn't reentrant

**Comment by Mandalka** [comment]
After temporary removing of complex (many dependencies) external import-export-app following more specific error on second IP:

Traceback:

File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/lib/python3/dist-packages/django/core/handlers/base.py" in _legacy_get_response
  244.             response = middleware_method(request)

File "/usr/lib/python3/dist-packages/django/middleware/common.py" in process_request
  63.         if self.should_redirect_with_slash(request):

File "/usr/lib/python3/dist-packages/django/middleware/common.py" in should_redirect_with_slash
  81.                 not is_valid_path(request.path_info, urlconf) and

File "/usr/lib/python3/dist-packages/django/urls/base.py" in is_valid_path
  158.         resolve(path, urlconf)

File "/usr/lib/python3/dist-packages/django/urls/base.py" in resolve
  27.     return get_resolver(urlconf).resolve(path)

File "/usr/lib/python3/dist-packages/django/urls/resolvers.py" in resolve
  364.             for pattern in self.url_patterns:

File "/usr/lib/python3/dist-packages/django/utils/functional.py" in __get__
  35.         res = instance.__dict__[self.name] = self.func(instance)

File "/usr/lib/python3/dist-packages/django/urls/resolvers.py" in url_patterns
  407.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)

File "/usr/lib/python3/dist-packages/django/utils/functional.py" in __get__
  35.         res = instance.__dict__[self.name] = self.func(instance)

File "/usr/lib/python3/dist-packages/django/urls/resolvers.py" in urlconf_module
  400.             return import_module(self.urlconf_name)

File "/usr/lib/python3.7/importlib/__init__.py" in import_module
  127.     return _bootstrap._gcd_import(name[level:], package, level)

File "/var/lib/opensemanticsearch/opensemanticsearch/urls.py" in <module>
  10. 	url(r'^api/', include('api.urls', namespace="api")),

File "/usr/lib/python3/dist-packages/django/conf/urls/__init__.py" in include
  50.         urlconf_module = import_module(urlconf_module)

File "/usr/lib/python3.7/importlib/__init__.py" in import_module
  127.     return _bootstrap._gcd_import(name[level:], package, level)

File "/var/lib/opensemanticsearch/api/urls.py" in <module>
  3. from api import views

File "/var/lib/opensemanticsearch/api/views.py" in <module>
  7. from opensemanticetl.tasks import delete

File "/usr/lib/python3/dist-packages/opensemanticetl/tasks.py" in <module>
  16. from etl_web import Connector_Web

File "/usr/lib/python3/dist-packages/opensemanticetl/etl_web.py" in <module>
  9. from lxml import etree

Exception Type: ImportError at /files/recrawl
Exception Value: Interpreter change detected - this module can only be loaded into one interpreter per process.

**Comment by Mandalka** [comment]
WSGIApplicationGroup %{GLOBAL}
in apache config seems to solve it.

**Comment by Mandalka** [comment]
Changed preconfigured Apache wsgi config of the package in https://github.com/opensemanticsearch/open-semantic-search-apps/commit/9f4e2d710b44cb0b6914710058ee43fe5716ec06
