### ISSUE TITLE
Separated path for Django sqlite DB

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search-apps#61]
Use a separated path for Django DB file (currently /var/lib/opensemanticsearch/db.sqlite3), so it can be mounted separated from Django apps in [Docker](https://github.com/opensemanticsearch/open-semantic-search/issues/104) volume to enable automatic updates/overwrite of apps by new release of Docker container without overwriting the config DB.

- move db.sqlite3 to /var/opensemanticsearch/db
- move /var/opensemanticsearch/ontologies and /var/opensemanticsearch/thumbnails to /var/opensemanticsearch/media/ so media root can point to subpath files instead /var/opensemanticsearch where the DB will be, too which should not be accessable by HTTP.

**Comment by Mandalka** [comment]
On Debian package upgrades, old directory structure will be moved automatically to new destination by https://github.com/opensemanticsearch/open-semantic-search-apps/blob/master/DEBIAN/postinst

**Comment by Mandalka** [comment]
New db, thumbnails and ontologies paths created by https://github.com/opensemanticsearch/open-semantic-search-apps/blob/master/DEBIAN/postinst and config in https://github.com/opensemanticsearch/open-semantic-search-apps/blob/master/src/opensemanticsearch/settings.py
