### ISSUE TITLE
Make hosts of microservices / REST-APIs configurable by environment variables

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search-apps#62]
Make hosts of microservices / REST-APIs like Solr, Tika called by Ontologies Manager configurable by environment variables, so we can configure them dynamic in/by [Docker](https://github.com/opensemanticsearch/open-semantic-search/issues/104) config without modifications of config files in containers.

**Comment by Mandalka** [comment]
Implemented same environment variables for used services (Tika and Solr) like in Docker container Open Semantic ETL.
