### ISSUE TITLE
django-import-export must be pinned to 1.2.0

### ISSUE THREAD

**Issue by clamor** [opensemanticsearch/open-semantic-search-apps#63]
and probably django as well, otherwise installation on a fresh Ubuntu bionic fails.

**Comment by Mandalka** [comment]
Pinned django-import-export to 1.2.0 by https://github.com/opensemanticsearch/open-semantic-search/commit/23a82bed1ca6f51cf6988ee61e59fab5a728be94 and https://github.com/opensemanticsearch/open-semantic-search-apps/commit/fce415a0d1e89dbf37380fe228d9db111c048481 so Deb package should install correctly if django-import-export not yet on system by former installations in yet compatible version.

Have to prove next days, if Django release version itself is a problem in newer Ubuntu releases.

**Comment by Mandalka** [comment]
Closing this issue, since pinning now removed since running in new Ubuntu LTS and new Debian 10.6
