### ISSUE TITLE
Tagging and annotation UI not working.

### ISSUE THREAD

**Issue by persuader** [opensemanticsearch/open-semantic-search-apps#9]
I have installed the open-semantic-search_17.07.13.deb in ubuntu Ubuntu 16.04.2 LTS

After clicking the tagging & annotation link below the search result it trows the following error.

```
Exception Value:	
module 'urllib' has no attribute 'quote_plus'
Exception Location:	/var/lib/opensemanticsearch/annotate/views.py in edit_annotation, line 127
Python Executable:	/usr/bin/python3
Python Version:	3.5.2
```

Fixed by modifying line 127 in /var/lib/opensemanticsearch/annotate/views.py to

`return HttpResponseRedirect( "{}?uri={}".format( reverse('annotate:create'), urllib.parse.quote_plus( uri ) ) ) # Redirect after POST`

**Comment by Mandalka** [comment]
Thanks for bugreport. [Fixed](https://github.com/opensemanticsearch/open-semantic-search-apps/commit/6b650505d563d658f498cc992bd8339884f45410).
